name: CI
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn type-check
      - run: yarn lint
  build:
    needs: test
    strategy:
      matrix:
        include:
          - os: macos-latest
            dist-target: 'macos'
          - os: ubuntu-latest
            dist-target: 'linux'
          - os: windows-latest
            dist-target: 'windows'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install --no-install-recommends -y libarchive-tools
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn dist:${{ matrix.dist-target }} --publish never
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.dist-target }}
          path: |
            dist/*.*
            !dist/*.yml
