name: Release
on:
  release:
    types:
      - prereleased
      - released
jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
      - run: yarn --frozen-lockfile
      - run: yarn type-check
      - run: yarn lint
      - run: yarn build
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_APP_PASSWORD: ${{ secrets.APPLE_ID_APP_PASSWORD }}
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true
